name: Validate

on:
  workflow_call:

jobs:
  validate:
    name: Validate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build test coverage
        run: make install test
      - name: Build docs
        run: make docs
      - name: Check code
        run: make check
      - name: Validate package
        run: make local
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/coverage